## Numpy array revisited: functions, methods, and slicing

We'll be moving towards simulating molecular dynamics, but before that we should better establish various methods for numpy arrays.

## Methods for arrays
Similar to what we saw in Python lists earlier, Numpy arrays also come with methods. The way to use them is by appending any numpy array you're working with with ".method_name()". For example, if we define a numpy array

In [1]:
import numpy as np
a=np.random.randint(0,10,20)
a

array([1, 9, 6, 9, 6, 0, 5, 1, 7, 9, 8, 8, 7, 3, 1, 4, 6, 4, 3, 4],
      dtype=int32)

we can use the following methods to get its maximum value, minimum value, average value, and standard deviation.

In [2]:
print(a.max())
print(a.min())
print(a.mean())
print(a.std())

9
0
5.05
2.836811590500856


A few more advanced methods. reshape() will reshape your array into a desired dimesion, as long as the size of the array is conserved:

In [3]:
a.reshape(4,5)

array([[1, 9, 6, 9, 6],
       [0, 5, 1, 7, 9],
       [8, 8, 7, 3, 1],
       [4, 6, 4, 3, 4]], dtype=int32)

If you only want to provide one dimension and let the function figure out the other (so that the size of the array is conserved), you can use -1 (or any negative number) as one of the arguments:

In [4]:
a.reshape(4,-1)

array([[1, 9, 6, 9, 6],
       [0, 5, 1, 7, 9],
       [8, 8, 7, 3, 1],
       [4, 6, 4, 3, 4]], dtype=int32)

In [5]:
a.reshape(2,-1)

array([[1, 9, 6, 9, 6, 0, 5, 1, 7, 9],
       [8, 8, 7, 3, 1, 4, 6, 4, 3, 4]], dtype=int32)

Note that this reshaping does not change the array $a$ itself - it merely return a reshaped array and shows it to you. The array $a$ is still unchanged.

In [6]:
print(a.reshape(2,-1))
print(a)

[[1 9 6 9 6 0 5 1 7 9]
 [8 8 7 3 1 4 6 4 3 4]]
[1 9 6 9 6 0 5 1 7 9 8 8 7 3 1 4 6 4 3 4]


If you want to pass a reshaped array on to a new array, maybe you'll start writing

In [7]:
a = np.arange(10)
anew = a.reshape(2,-1)
print(anew)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Remember mutability? If you do this then "anew" and "a" will refer to the same data. If I accidentally changed an element in "a", "anew" will be unintentionally affected too, even though "anew" is of a different shape!

In [8]:
a[0]=-999
anew

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

To avoid this, we use the copy() method to be careful, as is recommended earlier when we talked about mutability.

In [9]:
a = np.arange(10)
anew = a.reshape(2,-1).copy()
a[0] = -999
anew

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

So much for the reshape() method. 

One more method: we can flatten a higher-dimensional array into 1D using the flatten() method.

In [10]:
a = np.random.randint(0,10,[4,5])
a

array([[5, 0, 0, 1, 3],
       [0, 0, 9, 9, 2],
       [3, 1, 8, 2, 8],
       [7, 6, 7, 8, 7]], dtype=int32)

In [11]:
a.flatten()

array([5, 0, 0, 1, 3, 0, 0, 9, 9, 2, 3, 1, 8, 2, 8, 7, 6, 7, 8, 7],
      dtype=int32)

## Functions for arrays

Another way to operate on arrays is to use numpy functions. In constrast to methods, when we use functions the format is np.function_name(your_array). For example, there is the mean() function.

In [12]:
np.mean(a)

np.float64(4.3)

It generates the same result as a.mean() but numpy function sometimes offer finer control. For example, instead of taking the average of everything in a 2D array, we can take averages along rows or columns:

In [13]:
print(a)
np.mean(a, axis = 0) #taking the average of each column

[[5 0 0 1 3]
 [0 0 9 9 2]
 [3 1 8 2 8]
 [7 6 7 8 7]]


array([3.75, 1.75, 6.  , 5.  , 5.  ])

In [16]:
np.mean(a, axis = 1) #taking the average of each row

array([1.8, 4. , 4.4, 7. ])

Same with many other functions, like sum():

In [17]:
np.sum(a) #sum of everything

np.int64(86)

In [18]:
np.sum(a, axis=0) # sum of every column

array([15,  7, 24, 20, 20])

In [19]:
np.sum(a, axis=1) # sum of every row

array([ 9, 20, 22, 35])

# Accessing array elements, array slicing
Accessing elements:

In [20]:
#1D array examples
a=np.arange(1,21)

a[0]        #first element
a[-1]       #last element
a[[1,3]]    #2nd and 4th element
a[ a>10 ]   #all elements satisfying a condition

#2D array examples
b=np.arange(20).reshape(4,5)
b[0,1]      #element on 1st row, 2nd column
b[0]        #1st row 
b[0,:]      #1st row
b[:,0]      #first column

array([ 0,  5, 10, 15])

Slicing:

In [21]:

a[0:2]          #elements from index 0 to 2, including 0, excluding 2
a[2:4]          #elements from index 2 to 4, including 2, excluding 4
a[:]            #all elements
a[0:4:2]        #elements from index 0 to 4 in steps of 2
a[::2]          #all elements in steps of 2
a[-1:-4:-1]     #from last elements backwards in steps of  -1


array([20, 19, 18])

### A closer look at slicing with printed output

The cells above showed the syntax, but let's actually run them and see the results. We'll use a 1D array of integers 1–20 and a 2D array so we can compare.

In [22]:
import numpy as np

a = np.arange(1, 21)   # [1, 2, ..., 20]
print('full array:    ', a)
print('a[0:5]         ', a[0:5])       # first 5
print('a[::2]         ', a[::2])       # every other
print('a[1::2]        ', a[1::2])      # every other starting from index 1
print('a[-3:]         ', a[-3:])       # last 3
print('a[::-1]        ', a[::-1])      # reversed

full array:     [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
a[0:5]          [1 2 3 4 5]
a[::2]          [ 1  3  5  7  9 11 13 15 17 19]
a[1::2]         [ 2  4  6  8 10 12 14 16 18 20]
a[-3:]          [18 19 20]
a[::-1]         [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


Slicing a **2D array** works the same way but you supply two slice objects separated by a comma — one for rows and one for columns.

In [23]:
b = np.arange(1, 21).reshape(4, 5)
print('b =\n', b)
print()
print('b[0, :]      first row:      ', b[0, :])
print('b[:, 0]      first column:   ', b[:, 0])
print('b[1:3, 1:4]  inner 2x3 block:\n', b[1:3, 1:4])
print('b[::2, ::2]  every-other row & col:\n', b[::2, ::2])

b =
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

b[0, :]      first row:       [1 2 3 4 5]
b[:, 0]      first column:    [ 1  6 11 16]
b[1:3, 1:4]  inner 2x3 block:
 [[ 7  8  9]
 [12 13 14]]
b[::2, ::2]  every-other row & col:
 [[ 1  3  5]
 [11 13 15]]


**Why does this matter for MD?** In the molecular dynamics code we'll write next, the state array `y` stores positions and velocities for *all* particles in one flat array. We'll use step-2 slicing like `y[0:2*N:2]` (all x-coordinates) and `y[1:2*N:2]` (all z-coordinates) constantly.

## Fancy indexing

Beyond slices, numpy lets you index with *arrays of integers* or *boolean arrays*. This is called **fancy indexing**.

### Integer array indexing

In [24]:
a = np.array([10, 20, 30, 40, 50])

idx = np.array([0, 2, 4])    # pick elements 0, 2, 4
print(a[idx])                # [10 30 50]

# Works on 2D arrays too
b = np.arange(1, 13).reshape(3, 4)
print(b)
print(b[[0, 2], :])    # rows 0 and 2

[10 30 50]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


### Boolean (conditional) indexing

In [25]:
a = np.array([10, 20, 30, 40, 50])

mask = a > 25                 # boolean array
print('mask:   ', mask)
print('a>25:   ', a[mask])    # only elements where mask is True
print('a<35:   ', a[a < 35])  # inline condition

mask:    [False False  True  True  True]
a>25:    [30 40 50]
a<35:    [10 20 30]


### np.where()

`np.where(condition, value_if_true, value_if_false)` is a powerful alternative that returns a *new array* — very useful for applying boundary conditions.

In [26]:
speeds = np.array([0.5, 1.5, 2.3, 0.1, 3.0])

# clamp speeds above 2.0 back down to 2.0
clamped = np.where(speeds > 2.0, 2.0, speeds)
print('original:', speeds)
print('clamped: ', clamped)

original: [0.5 1.5 2.3 0.1 3. ]
clamped:  [0.5 1.5 2.  0.1 2. ]


In [27]:
# np.where with a single argument returns the *indices* where condition is True
a = np.array([5, -3, 8, -1, 0, 2])
neg_indices = np.where(a < 0)
print('indices of negatives:', neg_indices[0])
print('negative values:     ', a[neg_indices])

indices of negatives: [1 3]
negative values:      [-3 -1]


## Broadcasting

NumPy's **broadcasting** rules let you do arithmetic between arrays of *different shapes* without writing loops. The key rule: dimensions are compared from the right, and a size-1 dimension can be stretched to match any size.

In [28]:
# Simple 1D example: add a scalar to every element
a = np.array([1, 2, 3, 4])
print(a + 10)       # 10 is broadcast across all 4 elements

[11 12 13 14]


In [29]:
# Add a 1D array to every row of a 2D array
positions = np.array([[1.0, 0.0],
                       [2.0, 1.0],
                       [3.0, 2.0]])   # shape (3, 2): 3 particles, (x, z) coords

shift = np.array([0.5, -0.5])        # shape (2,): displacement to add to every particle

print('shifted positions:\n', positions + shift)  # shape (3,2) + (2,) = (3,2)

shifted positions:
 [[ 1.5 -0.5]
 [ 2.5  0.5]
 [ 3.5  1.5]]


**Physics example — computing pairwise displacement without a loop:**

Suppose we have $N$ particles and want to find the displacement from particle 0 to every other particle. Broadcasting makes this a one-liner.

In [31]:
# 4 particles, 2D positions
pos = np.array([[0.0, 0.0],
                [1.0, 0.5],
                [2.0, 1.0],
                [0.5, 1.5]])

# displacement from particle 0 to all others
delta = pos - pos[0]      # (4,2) - (2,) broadcasts correctly
print('displacements from particle 0:\n', delta)

displacements from particle 0:
 [[0.  0. ]
 [1.  0.5]
 [2.  1. ]
 [0.5 1.5]]


## Combining arrays: concatenate, vstack, hstack

Sometimes we need to glue arrays together. The main tools are `np.concatenate`, `np.vstack` (vertical stack = row-wise), and `np.hstack` (horizontal stack = column-wise).

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.concatenate([a, b]))     # [1 2 3 4 5 6]

# For 2D arrays:
A = np.ones((2, 3))
B = np.zeros((2, 3))
print('vstack (rows):\n',  np.vstack([A, B]))   # shape (4, 3)
print('hstack (cols):\n',  np.hstack([A, B]))   # shape (2, 6)

[1 2 3 4 5 6]
vstack (rows):
 [[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
hstack (cols):
 [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


### np.stack vs np.concatenate

`np.stack` creates a *new axis*, while `np.concatenate` joins along an *existing* axis.

In [33]:
xs = np.array([1.0, 2.0, 3.0])   # x-coordinates of 3 particles
zs = np.array([0.5, 1.5, 2.5])   # z-coordinates

# stack along axis=1 to get a (3,2) positions array  — very handy!
positions = np.stack([xs, zs], axis=1)
print('positions array (N x 2):\n', positions)
print('shape:', positions.shape)

positions array (N x 2):
 [[1.  0.5]
 [2.  1.5]
 [3.  2.5]]
shape: (3, 2)


## np.meshgrid — setting up a grid of points

`np.meshgrid` takes two 1D arrays and returns two 2D arrays that together give the coordinates of every point on a grid. This is exactly what we'll use to place particles on a regular lattice at the start of our MD simulation.

In [34]:
x = np.linspace(-2, 2, 3)   # 3 equally spaced x values
z = np.linspace(-1, 1, 3)   # 3 equally spaced z values

xgrid, zgrid = np.meshgrid(x, z)
print('xgrid:\n', xgrid)
print('zgrid:\n', zgrid)

xgrid:
 [[-2.  0.  2.]
 [-2.  0.  2.]
 [-2.  0.  2.]]
zgrid:
 [[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]


In [35]:
# To get a flat list of (x, z) coordinates for all grid points:
x_flat = xgrid.flatten()
z_flat = zgrid.flatten()
print('x positions of all 9 grid points:', x_flat)
print('z positions of all 9 grid points:', z_flat)

# Or as an (N, 2) array:
positions = np.stack([x_flat, z_flat], axis=1)
print('\nposition array (9 x 2):\n', positions)

x positions of all 9 grid points: [-2.  0.  2. -2.  0.  2. -2.  0.  2.]
z positions of all 9 grid points: [-1. -1. -1.  0.  0.  0.  1.  1.  1.]

position array (9 x 2):
 [[-2. -1.]
 [ 0. -1.]
 [ 2. -1.]
 [-2.  0.]
 [ 0.  0.]
 [ 2.  0.]
 [-2.  1.]
 [ 0.  1.]
 [ 2.  1.]]


## Linear algebra: dot products and norms

NumPy has built-in support for the linear algebra operations we need in physics.

In [36]:
# Dot product
v1 = np.array([1.0, 0.0])
v2 = np.array([0.0, 1.0])
v3 = np.array([1.0, 1.0])

print('v1 · v2 =', np.dot(v1, v2))   # 0 — perpendicular
print('v1 · v3 =', np.dot(v1, v3))   # 1

v1 · v2 = 0.0
v1 · v3 = 1.0


In [37]:
# Vector magnitude (norm)
r = np.array([3.0, 4.0])
print('|r| =', np.linalg.norm(r))   # should be 5.0

|r| = 5.0


**Computing inter-particle distances** is something we'll do constantly in MD. Given the positions of two particles, the distance is:

In [38]:
pos1 = np.array([1.0, 0.5])
pos2 = np.array([3.0, 2.5])

# Method 1: using np.linalg.norm
r12 = np.linalg.norm(pos2 - pos1)
print('distance =', r12)

# Method 2: manual (what the MD code uses for speed)
dx = pos2[0] - pos1[0]
dz = pos2[1] - pos1[1]
r12_manual = np.sqrt(dx**2 + dz**2)
print('distance =', r12_manual)

distance = 2.8284271247461903
distance = 2.8284271247461903


---
## Exercises

The following exercises are designed to practice the tools above in a context directly relevant to the MD simulation we'll build next.

### Exercise 1 — Slicing a state array

In our MD code the full state of $N$ particles is stored in a 1D array `y` of length $4N$, arranged as: `[x1, z1, x2, z2, ..., xN, zN, vx1, vz1, ..., vxN, vzN]`.

For `N = 3` particles, the array below represents the initial state. Use **slicing** (no loops!) to:
1. Extract all x-positions.
2. Extract all z-positions.
3. Extract the (x, z) velocity of particle 2 (0-indexed).
4. Reshape the first `2N` elements into an `(N, 2)` positions array.

In [42]:
N = 3
y = np.array([1.0, 0.5,   2.0, -1.0,   0.5, 2.0,    # positions x1,z1,x2,z2,x3,z3
              0.1, 0.3,  -0.2,  0.1,   0.4,-0.1])   # velocities

# 1. All x-positions  (every other element starting at index 0, up to 2*N)
x_pos = y[0:2*N:2]
print('x-positions:', x_pos)

# 2. All z-positions
z_pos = y[1:2*N:2]
print('z-positions:', z_pos)

# 3. Velocity of particle 2 (x, z)
vel_2 = y[2*N + 2*2 : 2*N + 2*2 + 2]
print('velocity of particle 2:', vel_2)

# 4. Positions reshaped to (N, 2)
pos_array = y[0:2*N].reshape(N, 2)
print('positions array:\n', pos_array)

x-positions: [1.  2.  0.5]
z-positions: [ 0.5 -1.   2. ]
velocity of particle 2: [ 0.4 -0.1]
positions array:
 [[ 1.   0.5]
 [ 2.  -1. ]
 [ 0.5  2. ]]


### Exercise 2 — Broadcasting: computing all pairwise displacements

Given the positions of 4 particles, compute the displacement vector from **particle 0** to **every other particle** using broadcasting (no loops). Then compute the scalar distance to each.

In [43]:
pos = np.array([[0.0, 0.0],
                [1.0, 0.0],
                [1.0, 1.0],
                [0.0, 1.0]])

# Displacement from particle 0 to all particles
delta = pos - pos[0]    # broadcasting: (4,2) - (2,)
print('displacements:\n', delta)

# Distance = magnitude of each row
# np.linalg.norm with axis=1 computes the norm of each row
distances = np.linalg.norm(delta, axis=1)
print('distances from particle 0:', distances)

displacements:
 [[0. 0.]
 [1. 0.]
 [1. 1.]
 [0. 1.]]
distances from particle 0: [0.         1.         1.41421356 1.        ]


### Exercise 3 — Setting up a particle grid with meshgrid

This is a preview of the MD initialization code. Set up a **3×3 grid** of particles in a box that goes from $-R$ to $+R$ in both directions, with `R = 10 * bohr` (use `bohr = 0.53e-10` m). Return the positions as a flat 1D array `y` in the format `[x1, z1, x2, z2, ...]`.

In [41]:
bohr = 0.53e-10
R = 10 * bohr
gridsize = 3
nparticles = gridsize**2

# Grid of x and z values (leave a little margin from the walls)
xpos = np.linspace(-0.9*R, 0.9*R, gridsize)
zpos = np.linspace(-0.9*R, 0.9*R, gridsize)

xgrid, zgrid = np.meshgrid(xpos, zpos)

# Flatten and interleave into [x1,z1,x2,z2,...]
y = np.zeros(2 * nparticles)
y[0::2] = xgrid.flatten()   # even indices = x
y[1::2] = zgrid.flatten()   # odd  indices = z

print('y has', len(y), 'elements for', nparticles, 'particles')
print('first 3 particles (x,z):')
for i in range(3):
    print(f'  particle {i}: x={y[2*i]:.3e} m, z={y[2*i+1]:.3e} m')

y has 18 elements for 9 particles
first 3 particles (x,z):
  particle 0: x=-4.770e-10 m, z=-4.770e-10 m
  particle 1: x=0.000e+00 m, z=-4.770e-10 m
  particle 2: x=4.770e-10 m, z=-4.770e-10 m
